name: C++ Ubuntu 18.04

on:
  push:
    branches: 
    - "master"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Run build script
      run: ./.github/scripts/run_build_ubuntu18_04.sh
